# Description: Configuration file for training a transformer model on the OPUS Books dataset
# I used this configuration file to train the model on a machine with 4 NVIDIA 3090 GPUs

dataset:
  ds_name: wmt14
  src_lang: en
  tgt_lang: de
  split: -1 # Automatically handled

model:
  num_heads: 8
  d_model: 512
  d_k: 64
  d_v: 64
  d_ff: 2048
  dropout: 0.1
  n_encoder_layers: 6
  n_decoder_layers: 6
  src_vocab_size: 32000
  tgt_vocab_size: 32000

training:
  max_global_steps: 100000
  # original -> 25k tokens per batch -> 25k / 4 = 6250 tokens per gpu
  tokens_per_step_per_gpu: 6250
  grad_accum_steps: 2
  n_gpus: 4
  lr: 1
  use_scheduler: true
  b1: 0.9
  b2: 0.98
  eps: 0.0000000001 # 1e-9
  warmup_steps: 4000
  checkpoint_dir: "checkpoints/distrib_wmt14"
  checkpoint_filename: "latest"
  checkpoint_save_filename: "checkpoint.pth"
  save_freq: 1000 # each 1000 steps
  label_smoothing: 0.1

eval:
  batch_size: 128
  checkpoint_dir: "checkpoints/distrib_wmt14"
  checkpoint_filename: "latest"
